### ISSUE TITLE
2 projects at the same time .. first database is killed

### ISSUE THREAD

**Issue by mvenghaus** [lando/mysql#22]
Hey,

when having 2 lando projects open the first database is killed when the second is started. In older lando version this was no problem .. maybe because i have the newest docker version!? anyone has the same issue?

database_1   | /launch.sh: line 11:    17 Killed                  /opt/bitnami/scripts/mysql/entrypoint.sh /opt/bitnami/scripts/mysql/run.sh

**Comment by gitressa** [comment]
Can you share the two `.lando.yml` files?

**Comment by mvenghaus** [comment]
```
name: mm-m1
recipe: lamp

proxy:
  appserver:
    - m1.test.dev

config:
  webroot: .
  php: '7.1'
  composer_version: '1.10.12'
  database: mysql:5.7
  xdebug: false
````

````
name: mm-m2
recipe: lamp

proxy:
  appserver:
    - m2.test.dev

config:
  webroot: pub
  php: 8.1
  composer_version: '2.3.7'
  database: mysql:5.7
  xdebug: true
````
