### ISSUE TITLE
Path to included my_custon.cnf has changed

### ISSUE THREAD

**Issue by ryanbrownellbounteous** [lando/mysql#24]
I have been trying to modify the MySQL settings for a container using MySQL 5.7. I have not been able to get anything to work.

I investigated the settings file located at `/opt/bitnami/mysql/conf/my.cnf` and found that the location specified in `services/mysql/builder.js` no longer matches the path for including custom `.cnf` files.

The new path appears to be `/opt/bitnami/mysql/conf/bitnami/my_custom.cnf`

**Comment by ryanbrownellbounteous** [comment]
I found a work-around for this issue by doing the following

```
services:
    database:
    type: mysql
    remoteFiles:
      database: '/opt/bitnami/mysql/conf/bitnami/my_custom.cnf'
```

In general there appears to be significant differences between implementation and documentation for this recipe.
