### ISSUE TITLE
Better Healthcheck Testing/Blank dbname/user Testing

### ISSUE THREAD

**Issue by reynoldsalec** [lando/mysql#45]
We just implemented a fix to handle situations where the user specifies blank dbname/password/username for the db config. Ex:

```
services:
  database:
    type: mysql
      creds:
        user: customusername
        password:
        database: customdbname
```

The fix: https://github.com/lando/mysql/commit/b78401f11c23499e2154808dbf17fa0910d83d7a

I put in a "test case" in the `custom` example to make sure a blank password wouldn't fail the healthcheck or otherwise create problems, however, I'm not testing blank `user` or `database` values. From some quick manual testing it looked like those worked ok, but would be good to explicitly test this.
