### ISSUE TITLE
Database healthcheck on GitHub Action throws warning

### ISSUE THREAD

**Issue by yorkshire-pudding** [lando/mysql#51]
I have a Lando recipe and GitHub action that runs tests.  I've just updated it to use the `lando/setup-lando@v3` gha (which works a treat btw)

Recipe: Backdrop
Lando version: "latest"
Database: mysql

When Lando is started, it mostly runs fine, but when it does the database health check this warning appears:
`Warning: LED] mysql: [Warning] Using a password on the command line interface can be insecure.`

I wonder if the healthcheck could switch to using a `.cnf` file for the creds to avoid this warning?

**Comment by yorkshire-pudding** [comment]
What I've done to avoid this: in my `.lando.yml` file, override the health check, thus:

```yaml
services:  
  database:
    healthcheck: mysql --defaults-extra-file=/app/.lando/mysql.cnf --silent --execute "SHOW DATABASES;"
```

and create in `/app/.lando/mysql.cnf`

```cnf
[client]
  user=backdrop
  password=backdrop
  host=database
```
